#!/bin/sh
# vim: foldmethod=marker

# Config {{{

bspc config border_width         1
bspc config window_gap           5
bspc config top_padding          25
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       true
# bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_by_distance    true
bspc config focus_follows_pointer true
# bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# }}}

# Colors {{{

bspc config normal_border_color		"#1e1e1e"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#3993DB"
bspc config presel_feedback_color	"#5e81ac"
# bspc config urgent_border_color 	"#dd2727"

# }}}

# Other {{{

# 10 workspaces on single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
# bspc monitor -d 9 10

# Set wmname to LG3D so java apps work properly
wmname LG3D

# Autostart
~/.config/bspwm/autostart.sh

# }}}

# Rules {{{

bspc rule -a flameshot state=floating
bspc rule -a Yad state=floating

# }}}
