#!/usr/bin/env sh

if bspc query --tree --node | grep --silent '"state":"floating"'; then
	case $1 in
		left) bspc node -v -20 0 ;;
		down) bspc node -v 0 +20 ;;
		right) bspc node -v +20 0 ;;
		up) bspc node -v 0 -20 ;;
		*) ;;
	esac
else
	case $1 in
		left) bspc node --swap west ;;
		down) bspc node --swap south ;;
		right) bspc node --swap east ;;
		up) bspc node --swap north ;;
		*) ;;
	esac
fi
