#!/usr/bin/env bash

case $1 in
	term) kitty -1 & disown ;;
	menu) rofi -no-lazy-grab -show drun -modi drun -theme ~/.config/rofi/launchers/misc/blurry.rasi & disown ;;
	screenshot-area) flameshot gui & disown ;;
	browser) firefox & disown ;;
	filemanager) dolphin & disown ;;
	emoji-picker) rofimoji --action copy --skin-tone neutral --rofi-args "-theme Arc-Dark" & disown ;;
	lock) betterlockscreen --lock & disown ;;
	*) ;;
esac
