#!/bin/sh

export USER="<username>"
export HOME="/home/<username>"

groups="$(id -Gn "$USER" | tr ' ' ':')"
svdir="${XDG_DATA_HOME:-$HOME/.local/share}/service"

exec chpst -u "$USER:$groups" runsvdir "$svdir"
