#!/usr/bin/env bash
# vim: foldmethod=marker

# Config {{{
bspc config border_width 1
bspc config window_gap 0
bspc config top_padding 25
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle true
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
# }}}

# Colors {{{
bspc config normal_border_color "#111111"
bspc config active_border_color "#111111"
bspc config focused_border_color "#9E9E9E"
bspc config presel_feedback_color "#9E9E9E"
# }}}

# Other {{{
# 10 workspaces on every monitor
for m in $(bspc query -M); do
	bspc monitor "$m" -d 1 2 3 4 5 6 7 8 9 10
done

# Set wmname to LG3D so java apps work properly
wmname LG3D
# }}}

# Rules {{{
bspc rule -a flameshot state=floating
bspc rule -a Peek state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a Yad state=floating
# }}}

# Autostart {{{

numlockx on
xorg-layouts
sens
xplugd & disown
xss-lock x-lock & disown
dunst & disown

SXHKD_SHELL=/usr/bin/sh sxhkd -c "${XDG_CONFIG_HOME:-$HOME/.config}"/bspwm/sxhkdrc & disown

xsetroot -cursor_name left_ptr
wp reset & disown

bspwm-state-prop & disown
picom -b --experimental-backends & disown

pipewire & disown
pipewire-pulse & disown

dex -a -v -e bspwm & disown

sleep 2
"${XDG_CONFIG_HOME:-$HOME/.config}"/polybar/launch.sh & disown

# }}}
