#!/bin/sh
# vim: foldmethod=marker

# Config {{{
bspc config border_width 1
bspc config window_gap 0
bspc config top_padding 25
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle true
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
# }}}

# Colors {{{
bspc config normal_border_color "#111111"
bspc config active_border_color "#111111"
bspc config focused_border_color "#9E9E9E"
bspc config presel_feedback_color "#9E9E9E"
# }}}

# Other {{{
# 10 workspaces on single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Set wmname to LG3D so java apps work properly
wmname LG3D
# }}}

# Rules {{{
bspc rule -a flameshot state=floating
bspc rule -a Peek state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a Yad state=floating
# }}}

# Autostart {{{
dex -a -v -e bspwm >/dev/null 2>&1 &
# }}}
