#!/usr/bin/env sh

if [ -f "/etc/X11/xorg.conf.d/10-nvidia-optimus.conf" ]; then
	xrandr --setprovideroutputsource modesetting NVIDIA-0
	xrandr --auto
	xrandr --dpi 96
fi

xorg-setup-display

export DESKTOP_SESSION="bspwm"

if command -v systemctl >/dev/null; then
	exec "$DESKTOP_SESSION"
else
	exec dbus-run-session "$DESKTOP_SESSION"
fi
